INSERT INTO `lubricantes` (`nombre`) VALUES
('2T ultra x 1l'),
('2T nautico x 1l'),
('4T x 1l'),
('suplemento 1 x 1l'),
('suplemento 1 x 4l'),
('suplemento x 20l'),
('AT turbo x 1l'),
('At turbo x 4'),
('AT turbo x 20l'),
('extra vida x 1l'),
('extra vida x 4l'),
('extra vida x 20l'),
('grasa 30c x 2kg'),
('grasa 30c x 5kg'),
('grasa 30c x 18kg'),
('grasa 62l x 2kg'),
('grasa 62l x 5kg'),
('grasa 62l x 18kg'),
('torque x 1l'),
('torque x 4l'),
('f10 x 1l'),
('f10 x 4l'),
('f30 x 1l'),
('f30 x 4l'),
('f50 x 1l'),
('f50 x 4l'),
('suv x 1l'),
('suv x 4l'),
('transmision x 4'),
('transmision x 20'),
('hipoidal x 4 '),
('hipoidal x 20'),
('hidraulico BP x 20'),
('hidro 19 x 20'),
('hidro ATF x 20'),
('extra vida x 20'),
('2T 100ml'),
('liquido freno x 1l'),
('2t 200 cc'),
('azul 32 x 10l'),
('liquido freno 200 ml'),
('mata MM'),
('transmision 500'),
('shampoo-lata gel'),
('lubripen'),
('liquido freno 500cc'),
('silicona'),
('agua destilada x 1l'),
('agua refrigerante x 1l'),
('agua destilada x 5l'),
('agua refrigerante x 5l'),
('gas 10kg'),
('gas x 15kg'),
('gas x 45kg');
